GET http://localhost:4200/movies/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:4200/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "profilePictureLink": "torrance.png",
  "name": "Jack",
  "password": "shining"
}

###

POST http://localhost:4200/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###
## Проверка токена пользователя
GET http://localhost:4200/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYzN2I1NGFiYzk1M2QzNDc3OTg4ZDZjMyIsImlhdCI6MTY2OTYzMDAwMSwiZXhwIjoxNjY5ODAyODAxfQ.P7uNG_Jge-nuA1txwE7AuzFQ48ZbYXxAktG9-W0XQzM

###

###
POST http://localhost:4200/comments HTTP/1.1
Content-Type: application/json

{
  "text": "1235678",
  "rating": 9,
  "author": "637b54abc953d3477988d6c3",
  "movieId": "6352ad1e45a88ec5bc632294"
}

###
## Список комментариев к фильму
GET http://localhost:4200/movies/6352ad1e45a88ec5bc632294/comments HTTP/1.1

###

## Отправка аватарки пользователю

POST http://localhost:4200/users/634971d0351d0b51b90a0040/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpg

F:\NaNe\potapov\avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

