openapi: '3.0.2'
info:
  title: API сервер для проекта «Что посмотреть».
  description: Список ресурсов и маршрутов сервера «Что посмотреть».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: '1.0.0'
tags:
  - name: movies
    description: Действия с фильмами.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.
  - name: favorites
    description: Действия со списком "К просмотру".
paths:
  /movies:
    post:
      tags:
        - movies
      summary: Добавление фильма
      description: Добавление новой карточки с фильмом
      requestBody:
        description: Данные для создания новой карточки с фильмом
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createMovie'
        required: true
      responses:
        '201':
          description: Новая карточка фильма добавлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'
    get:
      tags:
        - movies
      summary: Получение фильмов
      description: Получение списка фильмов
      responses:
        '200':
          description: Список фильмов получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/movie'

  /movies/{movieId}:
    get:
      tags:
        - movies
      summary: Получение данных фильма
      description: Получение детальной информации по фильму
      parameters:
        - in: path
          name: movieId
          schema:
            type: string
          required: true
          description: Идентификатор фильма
          example: aaa123
      responses:
        '200':
          description: Данные фильма получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'
    delete:
      tags:
        - movies
      summary: Удаление фильма
      description: Удаление карточки фильма
      parameters:
        - in: path
          name: movieId
          schema:
            type: string
          required: true
          description: Идентификатор фильма
          example: aaa123
      responses:
        '204':
          description: Фильм удален
    patch:
      tags:
        - movies
      summary: Изменить фильм
      description: Редактирование карточки фильма
      parameters:
        - in: path
          name: movieId
          schema:
            type: string
          required: true
          description: Идентификатор фильма
          example: aaa123
      requestBody:
        description: Измененные данные фильма
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createMovie'
      responses:
        '200':
          description: Фильм изменен

  /movies/promo:
    get:
      tags:
        - movies
      summary: Получение промо-фильма
      description: Получение промо-фильма
      responses:
        '200':
          description: Данные промо-фильма получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

  /movies/genre/{genre}:
    get:
      tags:
        - movies
      summary: Получение фильмов по жанру
      description: Получение фильмов по жанру
      responses:
        '200':
          description: Список фильмов по жанру получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/movie'

  /movies/{movieId}/comments:
    get:
      tags:
        - comments
      summary: Комментарии к фильму
      description: Получить список комментариев для определённого фильма
      responses:
        '200':
          description: Комментарии для фильма получены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'
        '404':
          description: Комментарии для фильма не найдены
          
  /movies/{movieId}/video:
    get:
      tags:
        - comments
      summary: Загрузка видео фильма
      description: Загрузить видео фильма
      responses:
        "201":
          description: Загружено видео фильма.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

  /movies/{movieId}/bg:
    get:
      tags:
        - comments
      summary: Загрузка заднего фона фильма
      description: Загрузить задний фон фильма
      responses:
        "201":
          description: Загружен задний фон фильма.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

  /movies/{movieId}/poster:
    get:
      tags:
        - comments
      summary: Загрузка постера фильма
      description: Загрузить постер фильма
      responses:
        "201":
          description: Загружен постер фильма.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

  /movies/{movieId}/preview:
    get:
      tags:
        - comments
      summary: Загрузка превью фильма
      description: Загрузить превью фильма
      responses:
        "201":
          description: Загружено превью фильма.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'
    

  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.
      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true
      responses:
        '201':
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '409':
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
      requestBody:
        description: Логин и пароль пользователя
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю
      responses:
        '200':
          description: Возвращает информацию по авторизованному пользователю
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара пользователя.
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате '.png' или '.jpg'.

      responses:
        "201":
          description: Загружено изображение аватара пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'



  /favorites:
    get:
      tags:
        - favorites
      summary: Получение фильмов к просмотру
      description: Получить список фильмов «К просмотру»
      responses:
        '200':
          description: Список фильмов «К просмотру» получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/movie'
    post:
      tags:
        - favorites
      summary: Добавление фильма в список "К просмотру"
      description: Добавление фильма в список "К просмотру"
      responses:
        '200':
          description: Фильм добавлен в список "К просмотру"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'
    delete:
      tags:
        - favorites
      summary: Удаление фильма из списка "К просмотру"
      description: Удаление фильма из списка "К просмотру"
      responses:
        '204':
          description: Фильм удален из списка "К просмотру"

  /comments:
    post:
      tags:
        - comments
      summary: Добавить комментарий
      description: Добавить новый комментарий к определённому фильму
      requestBody:
        required: true
        description: Данные для добавления комментария
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
      responses:
        '201':
          description: Создан комментарий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'

components:
  schemas:
    movie:
      type: object
      properties:
        id:
          type: string
          example: aaa123
        title:
          type: string
        description:
          type: string
        publicationDate:
          type: string
          format: date
        genre:
          type: string
          enum: [comedy, crime, documentary, drama, horror, family, romance, scifi, thriller]
        createdYear:
          type: integer
        rating:
          type: number
        videoPreviewLink:
          type: string
          format: uri
        videoLink:
          type: string
          format: uri
        actors:
          type: array
          items:
            type: string
        director:
          type: string
        movieDuration:
          type: integer
        commentAmount:
          type: integer
        userId:
          $ref: '#/components/schemas/user'
        posterLink:
          type: string
          format: uri
        backgroundPictureLink:
          type: string
          format: uri
        backgroundColor:
          type: string
          format: uri

    createMovie:
      type: object
      properties:
          title:
            type: string
            minLength: 2
            maxLength: 100
          description:
            type: string
            minLength: 20
            maxLength: 1024
          publicationDate:
            type: string
            format: date
          genre:
            type: string
            enum: [comedy, crime, documentary, drama, horror, family, romance, scifi, thriller]
          createdYear:
            type: integer
            minimum: 1880
          videoPreviewLink:
            type: string
            format: uri
          videoLink:
            type: string
            format: uri
          actors:
            type: array
            items:
              type: string
          director:
            type: string
            minLength: 2
            maxLength: 50
          movieDuration:
            type: integer
          commentAmount:
            type: number
          userId:
            type: string
          posterLink:
            type: string
            format: uri
          backgroundPictureLink:
            type: string
            format: uri
          backgroundColor:
            type: string
            format: uri

    comment:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 10
        date:
          type: string
          format: date-time
        author:
          $ref: '#/components/schemas/user'

    createComment:
      type: object
      properties:
        text:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 10
        author:
          type: string
        date:
          type: string
          format: date-time

    user:
      type: object
      properties:
        id:
          type: string
          example: aaa123
        email:
          type: string
          example: keks@htmlacademy.ru

    createUser:
      type: object
      properties:
        name:
          type: string
          example: Keks
        email:
          type: string
          example: keks@htmlacademy.ru
        password:
          type: string
          example: qwerty123